cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - client/.npm/
    - server/Main/.npm/

stages:
  - test
  - build
  - deploy_test

test:
  variables:
     BRANCH: '{ "branch": "${CI_COMMIT_REF_NAME}" }'
  stage: test
  script:
    #- Set-Location  client
    #- npm ci --cache .npm --prefer-offline
    #- npm run clean
    #- npm run recipe
    - Set-Location server/Test
    # Copy appsettings (how to connect to box). This is a server config file, available in /var/dotnet
    #- Copy-Item c:/gitlab-runner/testing-config/list/appsettings*.json .
    - dotnet test
  tags:
    - m4-instool

build:
  variables:
    BRANCH: '{ "branch": "${CI_COMMIT_REF_NAME}" }'
    ErrorActionPreference: stop
  stage: build
  script:
    #- Set-Location client
    #- npm ci --cache .npm --prefer-offline
    #- npm run clean
    #- npm run recipe
    #- npm run build
    - Set-Location server/Main
    - npm ci --cache .npm --prefer-offline
    - npm run clean
    - echo $env:BRANCH > branch.json
    - npm run release
    - Set-Location ../..
    - New-Item -ItemType Directory -Force -Path c:/gitlab-runner/versions/instool/$env:CI_COMMIT_REF_SLUG
    - Move-Item instool.zip c:/gitlab-runner/versions/instool/$env:CI_COMMIT_REF_SLUG/$((Get-Date).tostring("yyyy-MM-dd__hh-mm"))__$env:CI_COMMIT_SHORT_SHA.zip
    - npm run clean
  tags:
    - m4-instool

deploy_dev_manual:
    cache: {}
    stage: deploy_test
    variables:
      ErrorActionPreference: stop
      GIT_STRATEGY: none
    environment:
        name: dev
        url: https://m4-instool.vmhost.psu.edu
    when: manual
    except:
     - master
    script:
     - c:/gitlab-runner/scripts/deploy_version.ps1 -hash "$env:CI_COMMIT_SHORT_SHA" -app instool -site 'instool-dev'
    tags:
    - m4-instool